src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="10",max ="255",minMessage="Votre titre article est trop court")
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Commentaire::class, mappedBy="article", orphanRemoval=true)
     */
    private $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }

        return $this;
    }
}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Auteur;

    /**
     * @ORM\Column(type="text")
     */
    private $ContenuCommentaire;

    /**
     * @ORM\Column(type="string" , length=255)
     */
    private $DateCommentaire;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $article;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getContenuCommentaire(): ?string
    {
        return $this->ContenuCommentaire;
    }

    public function setContenuCommentaire(string $ContenuCommentaire): self
    {
        $this->ContenuCommentaire = $ContenuCommentaire;

        return $this;
    }

    public function getDateCommentaire(): ?String
    {
        return $this->DateCommentaire;
    }

    public function setDateCommentaire(string $DateCommentaire): self
    {
        $this->DateCommentaire = $DateCommentaire;
        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Categorie;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('Categorie', EntityType::class , [
                'class' => Categorie::class,
                'choice_label' => 'titreCategorie'

            ])
            ->add('contenu')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Form\ArticleType;

use App\Entity\Commentaire;
use App\Repository\CommentaireRepository;
use App\Form\CommentaireType;


class ArticleController extends AbstractController
{
    #[Route('/', name: 'article')]
    public function index(ArticleRepository $repo)
    {
        $articles = $repo->findAll();
        return $this->render('article/article.html.twig', [
            'active' => 'article',
            'articles' => $articles,
        ]);
    }

    #[Route('/new', name: 'new')]
    #[Route('/edit/{id}', name: 'edit')]
    public function form(Article $article= null , Request $request )
    {
        if($article == null){
            $article = new Article();
        }  
        $form = $this->createForm(ArticleType::class , $article );
        $form->handleRequest($request); 
        //dump($article);
        if($form->isSubmitTed() && $form->isValid()){
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($article);
            $manager->flush();

            $this->addFlash('noticeArticle', 'Insertion réussie => ID Artice : '.$article->getId().' | Titre article : '.$article->getTitre().' | Contenu : '.$article->getContenu().' ');
            return $this->redirectToRoute('article', [
                
            ]);
        }


        return $this->render('article/form.html.twig', [
            'active' => 'form',
            'formArticle' => $form->createView(),
            'editMode' => $article->getId() != null, 
        ]);
    }

    #[Route('/show/{id}', name: 'show')]
    public function show(Article $article, Request $request){
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        
        //on verfifier la requete
        $form->handleRequest($request); 
        if($form->isSubmitTed() && $form->isValid()){
            $manager = $this->getDoctrine()->getManager();
            $commentaire->setDateCommentaire(date("Y-m-d h:i:s"));
            $commentaire->setArticle($article);
            $manager->persist($commentaire);
            $manager->flush();
            return $this->redirectToRoute('show' , [
                'id' => $article->getId(),
            ]); 
            
        }
        return $this->render('article/show.html.twig', [
            'active' => 'article',
            'article' => $article,
            'formCommentaire'=>$form->createView()
        ]);

    }
}

templates/article/article.html.twig
{% extends 'base.html.twig' %}
{% block div %}
<!-- Page Content -->
            <div id="page-wrapper col-lg-12">
                <div class="container-fluid">
                    <div class="row"><br><br>
                        <div class="col-lg-12">
                            <h1 class="">Nos articles disponibles</h1>
                            <div class="panel col-lg-12">
                            {% for article in articles %}
                             <div class="bouclr"> <br>
                                <!-- /.row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="">
                                            <div class="col-lg-3">
                                                 <h4>Dans la categories : {{article.categorie.titreCategorie}}</h4>
                                                <img src="{{ asset('assets/placeholder/530x270.png') }}" width="300px" height="300px"/>
                                            </div>
                                            <div class="col-lg-9">
                                                <h1>{{article.titre}}</h1>
                                                <p>{{article.contenu}}
                                                </p>
                                                <p><a  href="{{ path('show', {'id':article.id})}}"  class="btn btn-primary btn-lg" role="button">Plus de details</a>
                                                    <a href="{{ path('edit', {'id':article.id})}}" class="btn btn-success btn-lg" role="button">Editer l'article</a>
                                                </p>
                                            </div>
                                            
                                        </div>
                                    </div>
                                    <!-- /.col-lg-12 -->
                                </div>
                                <!-- /.row --><hr>
                             </div><!-- boucle -->
                             {% endfor %}

                           <div>
                        </div>
                        
                        
                        <!-- /.col-lg-6 -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

{% endblock %}

templates/article/form.html.twig
{% extends 'base.html.twig' %}
{% form_theme formArticle 'bootstrap_4_layout.html.twig'  %}
{% block div %}
<!-- Page Content -->
            <div id="page-wrapper col-lg-12">
                <div class="container-fluid">
                    <div class="row"><br><br>
                        <div class="col-lg-12">
                            <h1 class="page-header">Formulaire </h1>
                        </div>
                        <div class="panel">
                            <!-- /.col-lg-6 -->
                        <div class="col-lg-12">
                                    
                            <!-- /.modal -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    Formulaire
                                </div>
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    
                                       {{ form_start(formArticle) }}
                                            {{ form_row(formArticle.titre , {'attr':{'class': "form-control"}}) }} 
                                            {{ form_row(formArticle.Categorie , {'attr':{'class': "form-control"}}) }}
                                            {{ form_row(formArticle.contenu , {'attr': {'class': "form-control" }}) }}
                                            <br>
                                            {% if editMode %}
                                                <button type="submit" class="btn btn-primary"> Sauvegarder la modification</button>
                                            {% else %}
                                                <button type="submit" class="btn btn-primary"> Inserer</button>
                                            {% endif %}
                                                {{ form_end(formArticle) }}
                                    
                                    
                                </div>
                                <!-- /.panel-body -->
                            </div>
                            <!-- /.panel -->
                        </div>
                        <!-- /.col-lg-6 -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}
{% block div %}
<!-- Page Content -->
            <div id="page-wrapper col-lg-12">
                <div class="container-fluid">
                    <div class="row"><br><br>
                        <div class="col-lg-12">
                            <h1 class="">Nos articles disponibles</h1>
                            <div class="panel col-lg-12">
                             <div class="boucle"> <br>
                                <!-- /.row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="">
                                            <div class="col-lg-3">
                                                 <h4>Dans la categories : {{article.categorie.titreCategorie}}</h4>
                                                <img src="{{ asset('assets/placeholder/530x270.png') }}" width="300px" height="300px"/>
                                            </div>
                                            <div class="col-lg-9">
                                                <h1>{{article.titre}}</h1>
                                                <p>{{article.contenu}}
                                                </p>
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.col-lg-12 -->
                                </div><br><br>
                                <!-- /.row -->
                                <!-- /.panel -->
                            <div class="chat-panel panel panel-default">
                                <div class="panel-heading">
                                    <i class="fa fa-comments fa-fw"></i>
                                     {{ article.commentaires | length }} commentaires
                                    
                                </div>
                                <!-- /.panel-heading -->
                                <div class="panel-body">
                                    <ul class="chat">
                                    {% for commentaire in article.commentaires %}
                                        <li class="left clearfix">
                                                <span class="chat-img pull-left">
                                                    <i class="fa fa-user"></i>
                                                </span>

                                            <div class="chat-body clearfix">
                                                <div class="header">
                                                    <strong class="primary-font">{{commentaire.auteur}}</strong>
                                                    <small class="pull-right text-muted">
                                                        <i class="fa fa-clock-o fa-fw"></i> le {{commentaire.dateCommentaire | date('d/m/Y à h:i:s')}}
                                                    </small>
                                                </div>
                                                <p>
                                                    {{commentaire.contenuCommentaire}}
                                                </p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                    </ul>
                                </div>
                                <!-- /.panel-body -->
                                <div class="panel-footer">
                                    {% if app.user %}
                                         {{ form_start(formCommentaire)}}
                                         {{ form_row(formCommentaire.Auteur , {'attr':{'class': "form-control"}}) }} 
                                         {{ form_row(formCommentaire.ContenuCommentaire , {'attr':{'class': "form-control"}}) }}
                                        <button type="submit" class="btn btn-success">Commenter</button>
                                        {{ form_end(formCommentaire)}}
                                    {% else %}
                                        <p>Vous devez connecter por commenter </p>
                                        <a class="btn btn-primary" href="{{ path('login') }}">Se connecter maintenant</a>
                                    {% endif %}
            
                                </div>
                             </div>

                           <div>
                        </div>
                        
                        
                        <!-- /.col-lg-6 -->
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->

{% endblock %}